// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// critical_points_cpp
Rcpp::List critical_points_cpp(const Rcpp::List& mesh, const std::string& scalar_field_name, bool compute_minima, bool compute_maxima, bool compute_saddle_points);
RcppExport SEXP _ttk_critical_points_cpp(SEXP meshSEXP, SEXP scalar_field_nameSEXP, SEXP compute_minimaSEXP, SEXP compute_maximaSEXP, SEXP compute_saddle_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mesh(meshSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type scalar_field_name(scalar_field_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_minima(compute_minimaSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_maxima(compute_maximaSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_saddle_points(compute_saddle_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(critical_points_cpp(mesh, scalar_field_name, compute_minima, compute_maxima, compute_saddle_points));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP ttk_contour_tree_cpp(SEXP, SEXP, SEXP);
RcppExport SEXP ttk_merge_tree_cpp(SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP ttk_morse_smale_complex_cpp(SEXP, SEXP, SEXP);
RcppExport SEXP ttk_persistence_diagram_cpp(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_ttk_critical_points_cpp", (DL_FUNC) &_ttk_critical_points_cpp, 5},
    {"ttk_contour_tree_cpp",        (DL_FUNC) &ttk_contour_tree_cpp,        3},
    {"ttk_merge_tree_cpp",          (DL_FUNC) &ttk_merge_tree_cpp,          4},
    {"ttk_morse_smale_complex_cpp", (DL_FUNC) &ttk_morse_smale_complex_cpp, 3},
    {"ttk_persistence_diagram_cpp", (DL_FUNC) &ttk_persistence_diagram_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ttk(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
